### ISSUE TITLE
Duplicate controllers

### ISSUE THREAD

**Issue by Rocketmagnet** [shadow-robot/sr-ronex#114]
Each time the Ronex SPI driver is run, it tries to add another controller. This generates an [ERROR]:

[ERROR] [1389712186.476177282]: A controller named 'ronex_1382696875_passthrough' was already loaded inside the controller manager

Each time the driver is re-run, the number of errors increases by 1.

**Comment by ugocupcic** [comment]
I think it's due to a weird problem with the parameters sometimes not being
removed from the param server when the driver is killed. It won't appear if
you don't keep the roscore running (ie don't start roscore, just do the
roslaunch)

On 14 January 2014 16:14, Rocketmagnet notifications@github.com wrote:

> Each time the Ronex SPI driver is run, it tries to add another controller.
> This generates an [ERROR]:
> 
> [ERROR] [1389712186.476177282]: A controller named
> 'ronex_1382696875_passthrough' was already loaded inside the controller
> manager
> 
> Each time the driver is re-run, the number of errors increases by 1.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/shadow-robot/sr-ronex-dev/issues/114
> .

## 

Ugo Cupcic _Senior Software Engineer_+44 20 7700 2487ugo@shadowrobot.com
www.shadowrobot.com

## 

---

_Shadow Robot Company Ltd._
251 Liverpool Road, N1 1LX, UK

## Registered Number 3308007 (England & Wales)
