### ISSUE TITLE
Ronex driver only works for a small range of serial numbers.

### ISSUE THREAD

**Issue by Rocketmagnet** [shadow-robot/sr-ronex#28]
Connect a Ronex node with serial number 0 to the PC. Run the driver. Stop the driver.
Connect a Ronex node with serial number 5 to the PC. Run the driver. Stop the driver.

Expected behaviour: The driver runs with no errors both times, and doesn't die.

Actual behaviour. Driver runs correctly with serial number 0, but dies with serial number 5 (or in fact any serial number that hasn't been listed in some file).

**Comment by toliver** [comment]
There are two problems here:
- The driver dying is cause because of the fact that there was a transmission defined in the sr_ronex_mechanism_model/example/ronex.urdf
  This transmission was using the ronex_33554433_0, so whenever you start the driver without having that module plugged in, the driver dies. It is normal. The transmission section for it should be commented out if the module is not going to be plugged in.
- When you plug a ronex with a different serial number, only the status topic shows up, but not the command topics. The reason for this is that the command topics are offered by the controller, so the user has (for the moment) to manually edit the sr_ronex_mechanism_model/example/ronex.launch file to add the controller for the new module to the spawner. It requires also to edit the 
  sr_ronex_controllers/config/general_io_passthrough_controller.yaml to add the necessary parameters for this new controller name.

**Comment by toliver** [comment]
The second point will be solved by #33 .

The first point it's not really an issue, as that is only an example urdf. The "plug and play launchfile" will not use any predefined transmissions. That is something that the user will have to customize for their robot following the examples we will provide (and only in the case they want to use the ronex for a joint based robot).

**Comment by ugocupcic** [comment]
Should be fixed too now.
